version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - oleg-nenashev
  - alecharp
  ignore:
  - dependency-name: io.jenkins.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.main:jenkins-core
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.plugins*
    versions:
    - ">= 0"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - "1.46"
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - "1.46"
